# define prune ratios for your network
prune_ratios:
  # stem.proj.weight: 
  #   0.5
  module.blocks.0.mlp_tokens.fc1.weight: 
    0.7
  module.blocks.0.mlp_tokens.fc2.weight: 
    0.7
  module.blocks.0.mlp_channels.fc1.weight: 
    0.7
  module.blocks.0.mlp_channels.fc2.weight: 
    0.7
  module.blocks.1.mlp_tokens.fc1.weight: 
    0.7
  module.blocks.1.mlp_tokens.fc2.weight: 
    0.7
  module.blocks.1.mlp_channels.fc1.weight: 
    0.7
  module.blocks.1.mlp_channels.fc2.weight: 
    0.7
  module.blocks.2.mlp_tokens.fc1.weight: 
    0.7
  module.blocks.2.mlp_tokens.fc2.weight: 
    0.7
  module.blocks.2.mlp_channels.fc1.weight: 
    0.7
  module.blocks.2.mlp_channels.fc2.weight: 
    0.7
  module.blocks.3.mlp_tokens.fc1.weight: 
    0.7
  module.blocks.3.mlp_tokens.fc2.weight: 
    0.7
  module.blocks.3.mlp_channels.fc1.weight: 
    0.7
  module.blocks.3.mlp_channels.fc2.weight: 
    0.7
  module.blocks.4.mlp_tokens.fc1.weight: 
    0.7
  module.blocks.4.mlp_tokens.fc2.weight: 
    0.7
  module.blocks.4.mlp_channels.fc1.weight: 
    0.7
  module.blocks.4.mlp_channels.fc2.weight: 
    0.7
  module.blocks.5.mlp_tokens.fc1.weight: 
    0.7
  module.blocks.5.mlp_tokens.fc2.weight: 
    0.7
  module.blocks.5.mlp_channels.fc1.weight: 
    0.7
  module.blocks.5.mlp_channels.fc2.weight: 
    0.7
  module.blocks.6.mlp_tokens.fc1.weight: 
    0.7
  module.blocks.6.mlp_tokens.fc2.weight: 
    0.7
  module.blocks.6.mlp_channels.fc1.weight: 
    0.7
  module.blocks.6.mlp_channels.fc2.weight: 
    0.7
  module.blocks.7.mlp_tokens.fc1.weight: 
    0.7
  module.blocks.7.mlp_tokens.fc2.weight: 
    0.7
  module.blocks.7.mlp_channels.fc1.weight: 
    0.7
  module.blocks.7.mlp_channels.fc2.weight: 
    0.7
  module.blocks.8.mlp_tokens.fc1.weight: 
    0.7
  module.blocks.8.mlp_tokens.fc2.weight: 
    0.7
  module.blocks.8.mlp_channels.fc1.weight: 
    0.7
  module.blocks.8.mlp_channels.fc2.weight: 
    0.7
  module.blocks.9.mlp_tokens.fc1.weight: 
    0.7
  module.blocks.9.mlp_tokens.fc2.weight: 
    0.7
  module.blocks.9.mlp_channels.fc1.weight: 
    0.7
  module.blocks.9.mlp_channels.fc2.weight: 
    0.7
  module.blocks.10.mlp_tokens.fc1.weight: 
    0.7
  module.blocks.10.mlp_tokens.fc2.weight: 
    0.7
  module.blocks.10.mlp_channels.fc1.weight: 
    0.7
  module.blocks.10.mlp_channels.fc2.weight: 
    0.7
  module.blocks.11.mlp_tokens.fc1.weight: 
    0.7
  module.blocks.11.mlp_tokens.fc2.weight: 
    0.7
  module.blocks.11.mlp_channels.fc1.weight: 
    0.7
  module.blocks.11.mlp_channels.fc2.weight: 
    0.7
  # head.weight: 
  #   0.5