# define prune ratios for your network
prune_ratios:
  # module.patch_embed.proj.weight:
  # 0.9
  module.layers.0.blocks.0.attn.qkv.weight:
  0.9
  module.layers.0.blocks.0.attn.proj.weight:
  0.9
  module.layers.0.blocks.0.mlp.fc1.weight:
  0.9
  module.layers.0.blocks.0.mlp.fc2.weight:
  0.9
  module.layers.0.blocks.1.attn.qkv.weight:
  0.9
  module.layers.0.blocks.1.attn.proj.weight:
  0.9
  module.layers.0.blocks.1.mlp.fc1.weight:
  0.9
  module.layers.0.blocks.1.mlp.fc2.weight:
  0.9
  module.layers.0.downsample.reduction.weight:
  0.9
  module.layers.1.blocks.0.attn.qkv.weight:
  0.9
  module.layers.1.blocks.0.attn.proj.weight:
  0.9
  module.layers.1.blocks.0.mlp.fc1.weight:
  0.9
  module.layers.1.blocks.0.mlp.fc2.weight:
  0.9
  module.layers.1.blocks.1.attn.qkv.weight:
  0.9
  module.layers.1.blocks.1.attn.proj.weight:
  0.9
  module.layers.1.blocks.1.mlp.fc1.weight:
  0.9
  module.layers.1.blocks.1.mlp.fc2.weight:
  0.9
  module.layers.1.downsample.reduction.weight:
  0.9
  module.layers.2.blocks.0.attn.qkv.weight:
  0.9
  module.layers.2.blocks.0.attn.proj.weight:
  0.9
  module.layers.2.blocks.0.mlp.fc1.weight:
  0.9
  module.layers.2.blocks.0.mlp.fc2.weight:
  0.9
  module.layers.2.blocks.1.attn.qkv.weight:
  0.9
  module.layers.2.blocks.1.attn.proj.weight:
  0.9
  module.layers.2.blocks.1.mlp.fc1.weight:
  0.9
  module.layers.2.blocks.1.mlp.fc2.weight:
  0.9
  module.layers.2.blocks.2.attn.qkv.weight:
  0.9
  module.layers.2.blocks.2.attn.proj.weight:
  0.9
  module.layers.2.blocks.2.mlp.fc1.weight:
  0.9
  module.layers.2.blocks.2.mlp.fc2.weight:
  0.9
  module.layers.2.blocks.3.attn.qkv.weight:
  0.9
  module.layers.2.blocks.3.attn.proj.weight:
  0.9
  module.layers.2.blocks.3.mlp.fc1.weight:
  0.9
  module.layers.2.blocks.3.mlp.fc2.weight:
  0.9
  module.layers.2.blocks.4.attn.qkv.weight:
  0.9
  module.layers.2.blocks.4.attn.proj.weight:
  0.9
  module.layers.2.blocks.4.mlp.fc1.weight:
  0.9
  module.layers.2.blocks.4.mlp.fc2.weight:
  0.9
  module.layers.2.blocks.5.attn.qkv.weight:
  0.9
  module.layers.2.blocks.5.attn.proj.weight:
  0.9
  module.layers.2.blocks.5.mlp.fc1.weight:
  0.9
  module.layers.2.blocks.5.mlp.fc2.weight:
  0.9
  module.layers.2.blocks.6.attn.qkv.weight:
  0.9
  module.layers.2.blocks.6.attn.proj.weight:
  0.9
  module.layers.2.blocks.6.mlp.fc1.weight:
  0.9
  module.layers.2.blocks.6.mlp.fc2.weight:
  0.9
  module.layers.2.blocks.7.attn.qkv.weight:
  0.9
  module.layers.2.blocks.7.attn.proj.weight:
  0.9
  module.layers.2.blocks.7.mlp.fc1.weight:
  0.9
  module.layers.2.blocks.7.mlp.fc2.weight:
  0.9
  module.layers.2.blocks.8.attn.qkv.weight:
  0.9
  module.layers.2.blocks.8.attn.proj.weight:
  0.9
  module.layers.2.blocks.8.mlp.fc1.weight:
  0.9
  module.layers.2.blocks.8.mlp.fc2.weight:
  0.9
  module.layers.2.blocks.9.attn.qkv.weight:
  0.9
  module.layers.2.blocks.9.attn.proj.weight:
  0.9
  module.layers.2.blocks.9.mlp.fc1.weight:
  0.9
  module.layers.2.blocks.9.mlp.fc2.weight:
  0.9
  module.layers.2.blocks.10.attn.qkv.weight:
  0.9
  module.layers.2.blocks.10.attn.proj.weight:
  0.9
  module.layers.2.blocks.10.mlp.fc1.weight:
  0.9
  module.layers.2.blocks.10.mlp.fc2.weight:
  0.9
  module.layers.2.blocks.11.attn.qkv.weight:
  0.9
  module.layers.2.blocks.11.attn.proj.weight:
  0.9
  module.layers.2.blocks.11.mlp.fc1.weight:
  0.9
  module.layers.2.blocks.11.mlp.fc2.weight:
  0.9
  module.layers.2.blocks.12.attn.qkv.weight:
  0.9
  module.layers.2.blocks.12.attn.proj.weight:
  0.9
  module.layers.2.blocks.12.mlp.fc1.weight:
  0.9
  module.layers.2.blocks.12.mlp.fc2.weight:
  0.9
  module.layers.2.blocks.13.attn.qkv.weight:
  0.9
  module.layers.2.blocks.13.attn.proj.weight:
  0.9
  module.layers.2.blocks.13.mlp.fc1.weight:
  0.9
  module.layers.2.blocks.13.mlp.fc2.weight:
  0.9
  module.layers.2.blocks.14.attn.qkv.weight:
  0.9
  module.layers.2.blocks.14.attn.proj.weight:
  0.9
  module.layers.2.blocks.14.mlp.fc1.weight:
  0.9
  module.layers.2.blocks.14.mlp.fc2.weight:
  0.9
  module.layers.2.blocks.15.attn.qkv.weight:
  0.9
  module.layers.2.blocks.15.attn.proj.weight:
  0.9
  module.layers.2.blocks.15.mlp.fc1.weight:
  0.9
  module.layers.2.blocks.15.mlp.fc2.weight:
  0.9
  module.layers.2.blocks.16.attn.qkv.weight:
  0.9
  module.layers.2.blocks.16.attn.proj.weight:
  0.9
  module.layers.2.blocks.16.mlp.fc1.weight:
  0.9
  module.layers.2.blocks.16.mlp.fc2.weight:
  0.9
  module.layers.2.blocks.17.attn.qkv.weight:
  0.9
  module.layers.2.blocks.17.attn.proj.weight:
  0.9
  module.layers.2.blocks.17.mlp.fc1.weight:
  0.9
  module.layers.2.blocks.17.mlp.fc2.weight:
  0.9
  module.layers.2.downsample.reduction.weight:
  0.9
  module.layers.3.blocks.0.attn.qkv.weight:
  0.9
  module.layers.3.blocks.0.attn.proj.weight:
  0.9
  module.layers.3.blocks.0.mlp.fc1.weight:
  0.9
  module.layers.3.blocks.0.mlp.fc2.weight:
  0.9
  module.layers.3.blocks.1.attn.qkv.weight:
  0.9
  module.layers.3.blocks.1.attn.proj.weight:
  0.9
  module.layers.3.blocks.1.mlp.fc1.weight:
  0.9
  module.layers.3.blocks.1.mlp.fc2.weight:
  0.9
  # module.head.weight:
  # 0.9