# define prune ratios for your network
prune_ratios:
    # module.patch_embed.proj.weight:
    #     0.7
    module.layers.0.blocks.0.attn.qkv.weight:
        0.7
    module.layers.0.blocks.0.attn.proj.weight:
        0.7
    module.layers.0.blocks.0.mlp.fc1.weight:
        0.7
    module.layers.0.blocks.0.mlp.fc2.weight:
        0.7
    module.layers.0.blocks.1.attn.qkv.weight:
        0.7
    module.layers.0.blocks.1.attn.proj.weight:
        0.7
    module.layers.0.blocks.1.mlp.fc1.weight:
        0.7
    module.layers.0.blocks.1.mlp.fc2.weight:
        0.7
    module.layers.0.downsample.reduction.weight:
        0.7
    module.layers.1.blocks.0.attn.qkv.weight:
        0.7
    module.layers.1.blocks.0.attn.proj.weight:
        0.7
    module.layers.1.blocks.0.mlp.fc1.weight:
        0.7
    module.layers.1.blocks.0.mlp.fc2.weight:
        0.7
    module.layers.1.blocks.1.attn.qkv.weight:
        0.7
    module.layers.1.blocks.1.attn.proj.weight:
        0.7
    module.layers.1.blocks.1.mlp.fc1.weight:
        0.7
    module.layers.1.blocks.1.mlp.fc2.weight:
        0.7
    module.layers.1.downsample.reduction.weight:
        0.7
    module.layers.2.blocks.0.attn.qkv.weight:
        0.7
    module.layers.2.blocks.0.attn.proj.weight:
        0.7
    module.layers.2.blocks.0.mlp.fc1.weight:
        0.7
    module.layers.2.blocks.0.mlp.fc2.weight:
        0.7
    module.layers.2.blocks.1.attn.qkv.weight:
        0.7
    module.layers.2.blocks.1.attn.proj.weight:
        0.7
    module.layers.2.blocks.1.mlp.fc1.weight:
        0.7
    module.layers.2.blocks.1.mlp.fc2.weight:
        0.7
    module.layers.2.blocks.2.attn.qkv.weight:
        0.7
    module.layers.2.blocks.2.attn.proj.weight:
        0.7
    module.layers.2.blocks.2.mlp.fc1.weight:
        0.7
    module.layers.2.blocks.2.mlp.fc2.weight:
        0.7
    module.layers.2.blocks.3.attn.qkv.weight:
        0.7
    module.layers.2.blocks.3.attn.proj.weight:
        0.7
    module.layers.2.blocks.3.mlp.fc1.weight:
        0.7
    module.layers.2.blocks.3.mlp.fc2.weight:
        0.7
    module.layers.2.blocks.4.attn.qkv.weight:
        0.7
    module.layers.2.blocks.4.attn.proj.weight:
        0.7
    module.layers.2.blocks.4.mlp.fc1.weight:
        0.7
    module.layers.2.blocks.4.mlp.fc2.weight:
        0.7
    module.layers.2.blocks.5.attn.qkv.weight:
        0.7
    module.layers.2.blocks.5.attn.proj.weight:
        0.7
    module.layers.2.blocks.5.mlp.fc1.weight:
        0.7
    module.layers.2.blocks.5.mlp.fc2.weight:
        0.7
    module.layers.2.downsample.reduction.weight:
        0.7
    module.layers.3.blocks.0.attn.qkv.weight:
        0.7
    module.layers.3.blocks.0.attn.proj.weight:
        0.7
    module.layers.3.blocks.0.mlp.fc1.weight:
        0.7
    module.layers.3.blocks.0.mlp.fc2.weight:
        0.7
    module.layers.3.blocks.1.attn.qkv.weight:
        0.7
    module.layers.3.blocks.1.attn.proj.weight:
        0.7
    module.layers.3.blocks.1.mlp.fc1.weight:
        0.7
    module.layers.3.blocks.1.mlp.fc2.weight:
        0.7
    # module.head.weight:
    #     0.7